### ISSUE TITLE
Contact Information Import

### ISSUE THREAD

**Issue by craigsander** [craigsander/evergreen#3]
``` python
[csander@localhost pas]$ python manage.py shell
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib64/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/csander/centriole/development/evergreen-tester/pas/evergreen/website/account/models.py", line 14, in <module>
    from evergreen.utils import contact_information as ci
ImportError: cannot import name contact_information
```

Happens on makemigrations account. 

Cause is likely an unpushed update to account/models.py

**Comment by craigsander** [comment]
Fixed.
